apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro-config
  labels:
    app: cerebro
data:
  host.conf: |
    hosts = [
      {
        host = "http://localhost:9200"
        name = "Some Cluster"
      }
    ]